// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9OaTkUcEF4NxnMC_llg04e_-tKjrF6Oc',
    appId: '1:427034677473:web:2ed699830c880ccb43e7a0',
    messagingSenderId: '427034677473',
    projectId: 'projecto-375cc',
    authDomain: 'projecto-375cc.firebaseapp.com',
    storageBucket: 'projecto-375cc.firebasestorage.app',
    measurementId: 'G-539LF5TXWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr3wBe4Q2Eqw1tH7rsVxJrLRZ4IV53wFg',
    appId: '1:427034677473:android:5848be1af5a91eb943e7a0',
    messagingSenderId: '427034677473',
    projectId: 'projecto-375cc',
    storageBucket: 'projecto-375cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQRS5M_xUozSeuTEw-JgiHZawPIdNppE',
    appId: '1:427034677473:ios:90b240589ae2549c43e7a0',
    messagingSenderId: '427034677473',
    projectId: 'projecto-375cc',
    storageBucket: 'projecto-375cc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFQRS5M_xUozSeuTEw-JgiHZawPIdNppE',
    appId: '1:427034677473:ios:90b240589ae2549c43e7a0',
    messagingSenderId: '427034677473',
    projectId: 'projecto-375cc',
    storageBucket: 'projecto-375cc.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrudnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9OaTkUcEF4NxnMC_llg04e_-tKjrF6Oc',
    appId: '1:427034677473:web:2ed699830c880ccb43e7a0',
    messagingSenderId: '427034677473',
    projectId: 'projecto-375cc',
    authDomain: 'projecto-375cc.firebaseapp.com',
    storageBucket: 'projecto-375cc.firebasestorage.app',
    measurementId: 'G-539LF5TXWM',
  );

}